#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # get users tweets
    timeline = helpers.get_user_timeline(sys.argv[1].lstrip("@"), 50)
    if timeline == None:
        sys.exit("could not retrieve tweets")
    
    # absolute path to list of negative and positives words
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # analyze tweets
    for tweet in timeline:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("  {} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("  {} {}".format(score, tweet), "red"))
        else:
            print(colored("  {} {}".format(score, tweet), "yellow"))
           
if __name__ == "__main__":
    main()